import "server-only";
import type { DocumentEditInput, DocumentListInput, DocumentOwnerType, UploadCompletionInput } from "@/features/documents/document-schema";
import { createClient } from "@/lib/supabase/server";

export const DOCUMENTS_PER_PAGE = 10;
export type DocumentValidity = "valid" | "expiring" | "expired" | "no_expiry" | "archived";
export type DocumentListItem = Readonly<{ id:string; fileName:string; documentType:string; ownerType:DocumentOwnerType; ownerLabel:string; lifecycleStatus:"active"|"archived"; validFrom:string|null; validUntil:string|null; validity:DocumentValidity; uploadedAt:string; updatedAt:string }>;
export type DocumentOwnerOption = Readonly<{ id:string; label:string }>;
export type EditableDocument = Readonly<{ id:string; documentType:string; ownerType:DocumentOwnerType; ownerLabel:string; validFrom:string|null; validUntil:string|null; updatedAt:string }>;
type Error = { category:"forbidden"|"not_found"|"conflict"|"business_rule"|"infrastructure"; message:string };
type Result<T> = { ok:true; data:T } | { ok:false; error:Error };
function translate(message:string):Error { if(message.includes("access_denied")) return {category:"forbidden",message:"Access denied."}; if(message.includes("not_found")) return {category:"not_found",message:"Document unavailable."}; if(message.includes("stale")) return {category:"conflict",message:"Document changed since you opened it. Reload and try again."}; if(message.includes("invalid")||message.includes("ineligible")) return {category:"business_rule",message:"Check the document details and try again."}; return {category:"infrastructure",message:"Unable to manage documents right now."}; }
export async function listDocuments(input:DocumentListInput):Promise<Result<{documents:readonly DocumentListItem[];totalCount:number;totalPages:number}>> { const client=await createClient(); const {data,error}=await client.rpc("list_operations_documents",{search_text:input.search,owner_filter:input.owner==="all"?undefined:input.owner,type_filter:input.type==="all"?undefined:input.type,lifecycle_filter:input.lifecycle,validity_filter:input.validity==="all"?undefined:input.validity,requested_page:input.page}); if(error)return{ok:false,error:translate(error.message)}; const totalCount=Number(data[0]?.total_count??0); return{ok:true,data:{documents:data.map((r)=>({id:r.id,fileName:r.file_name,documentType:r.document_type,ownerType:r.owner_type as DocumentOwnerType,ownerLabel:r.owner_label,lifecycleStatus:r.lifecycle_status,validFrom:r.valid_from,validUntil:r.valid_until,validity:r.derived_status as DocumentValidity,uploadedAt:r.uploaded_at,updatedAt:r.updated_at})),totalCount,totalPages:Math.ceil(totalCount/DOCUMENTS_PER_PAGE)}}; }
export async function listOwnerOptions(ownerType:DocumentOwnerType):Promise<Result<readonly DocumentOwnerOption[]>> { const client=await createClient(); const {data,error}=await client.rpc("list_document_owner_options",{owner_kind:ownerType}); return error?{ok:false,error:translate(error.message)}:{ok:true,data:data.map((r)=>({id:r.id,label:r.label}))}; }
export async function getDocumentForEdit(id:string):Promise<Result<EditableDocument>> { const client=await createClient(); const {data,error}=await client.rpc("get_operations_document_for_edit",{target_document_id:id}); if(error)return{ok:false,error:translate(error.message)}; const r=data[0]; return r?{ok:true,data:{id:r.id,documentType:r.document_type,ownerType:r.owner_type as DocumentOwnerType,ownerLabel:r.owner_label,validFrom:r.valid_from,validUntil:r.valid_until,updatedAt:r.updated_at}}:{ok:false,error:{category:"not_found",message:"Document unavailable."}}; }
export async function finalizeUpload(input:UploadCompletionInput):Promise<Result<string>> { const client=await createClient(); const {data,error}=await client.rpc("complete_document_upload",{target_document_id:input.documentId,owner_kind:input.ownerType,target_owner_id:input.ownerId,input_document_type:input.documentType,input_file_path:input.filePath,input_file_name:input.fileName,input_valid_from:input.validFrom??undefined,input_valid_until:input.validUntil??undefined}); return error?{ok:false,error:translate(error.message)}:{ok:true,data}; }
export async function updateDocument(input:DocumentEditInput):Promise<Result<"updated"|"noop">> { const client=await createClient(); const {data,error}=await client.rpc("update_document_metadata",{target_document_id:input.documentId,expected_updated_at:input.expectedUpdatedAt,input_document_type:input.documentType,input_valid_from:input.validFrom??undefined,input_valid_until:input.validUntil??undefined}); return error?{ok:false,error:translate(error.message)}:{ok:true,data:data==="noop"?"noop":"updated"}; }
export async function changeDocumentLifecycle(id:string,expectedUpdatedAt:string,status:"active"|"archived"):Promise<Result<"updated"|"noop">> { const client=await createClient(); const {data,error}=await client.rpc("set_document_lifecycle",{target_document_id:id,expected_updated_at:expectedUpdatedAt,requested_status:status}); return error?{ok:false,error:translate(error.message)}:{ok:true,data:data==="noop"?"noop":"updated"}; }

