import Link from "next/link";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Pagination, PaginationItem, PaginationLink, PaginationNext, PaginationPrevious } from "@/components/ui/pagination";
import { Select } from "@/components/ui/select";
import { StatusBadge } from "@/components/ui/status-badge";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { TableCard } from "@/components/ui/table-card";
import { TableScrollArea } from "@/components/ui/table-scroll-area";
import { TableToolbar } from "@/components/ui/table-toolbar";
import type { AlertListItem } from "@/lib/dal/alerts";
import type { AlertListInput } from "./alert-schema";

const typeLabels = { shipment_delayed: "Shipment delayed", document_expiring: "Document expiring", document_expired: "Document expired", maintenance_due_date: "Maintenance due date", maintenance_due_mileage: "Maintenance due mileage", stale_vehicle_location: "Stale vehicle location" } as const;
const formatter = new Intl.DateTimeFormat("en-GB", { year: "numeric", month: "short", day: "numeric", hour: "2-digit", minute: "2-digit", timeZone: "Europe/Belgrade", timeZoneName: "short" });
function url(filters: AlertListInput, page: number) { const p = new URLSearchParams(); if (filters.search) p.set("search", filters.search); if (filters.state !== "active") p.set("state", filters.state); if (filters.severity !== "all") p.set("severity", filters.severity); if (filters.type !== "all") p.set("type", filters.type); if (filters.entity !== "all") p.set("entity", filters.entity); if (page > 1) p.set("page", String(page)); const q = p.toString(); return q ? `/operations/alerts?${q}` : "/operations/alerts"; }

export function AlertList({ alerts, filters, totalCount, totalPages }: Readonly<{ alerts: readonly AlertListItem[]; filters: AlertListInput; totalCount: number; totalPages: number }>) {
  const footer = totalPages > 1 ? <Pagination><PaginationItem>{filters.page === 1 ? <PaginationPrevious disabled /> : <PaginationPrevious href={url(filters, filters.page - 1)} />}</PaginationItem>{Array.from({ length: totalPages }, (_, i) => i + 1).map((page) => <PaginationItem key={page}><PaginationLink href={url(filters, page)} active={page === filters.page}>{page}</PaginationLink></PaginationItem>)}<PaginationItem>{filters.page === totalPages ? <PaginationNext disabled /> : <PaginationNext href={url(filters, filters.page + 1)} />}</PaginationItem></Pagination> : undefined;
  return <div className="flex min-w-0 flex-col gap-4">
    <form action="/operations/alerts" method="get"><TableToolbar leading={<><div className="flex min-w-[min(100%,16rem)] flex-1 flex-col gap-1"><label className="sr-only" htmlFor="alert-search">Search alert messages</label><Input id="alert-search" name="search" type="search" defaultValue={filters.search} maxLength={100} placeholder="Search alert messages" focusSurface="card" /></div><Select aria-label="Alert state" name="state" defaultValue={filters.state} focusSurface="card"><option value="active">Active</option><option value="resolved">Resolved</option><option value="all">All states</option></Select><Select aria-label="Alert severity" name="severity" defaultValue={filters.severity} focusSurface="card"><option value="all">All severities</option><option value="info">Info</option><option value="warning">Warning</option><option value="critical">Critical</option></Select><Select aria-label="Alert type" name="type" defaultValue={filters.type} focusSurface="card"><option value="all">All types</option>{Object.entries(typeLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select><Select aria-label="Related entity" name="entity" defaultValue={filters.entity} focusSurface="card"><option value="all">All entities</option><option value="shipment">Shipment</option><option value="vehicle">Vehicle</option><option value="driver">Driver</option><option value="document">Document</option></Select></>} trailing={<><Button type="submit" variant="outline" focusSurface="card">Apply</Button><Link href="/operations/alerts" className="inline-flex min-h-11 items-center justify-center rounded-control px-4 text-label text-secondary hover:bg-background-hover md:min-h-10">Clear</Link></>} /></form>
    <TableCard title="Alerts" description={`${totalCount} ${totalCount === 1 ? "alert" : "alerts"}`} footer={footer}><TableScrollArea aria-label="Operations alerts table"><Table><TableHeader><TableRow><TableHead>Alert</TableHead><TableHead>Severity</TableHead><TableHead>Entity</TableHead><TableHead>Created</TableHead><TableHead>Status</TableHead><TableHead>Resolution</TableHead></TableRow></TableHeader><TableBody>{alerts.length === 0 ? <TableRow><TableCell colSpan={6} className="text-center text-secondary">No alerts found.</TableCell></TableRow> : alerts.map((alert) => <TableRow key={alert.id}><TableCell><p className="font-medium">{typeLabels[alert.type]}</p><p className="mt-1 max-w-xl text-small text-secondary">{alert.message}</p></TableCell><TableCell><StatusBadge domain="alert_severity" status={alert.severity} /></TableCell><TableCell>{alert.entityHref ? <Link className="font-medium text-primary hover:underline" href={alert.entityHref}>{alert.entityLabel}</Link> : alert.entityLabel}</TableCell><TableCell><time dateTime={alert.createdAt}>{formatter.format(new Date(alert.createdAt))}</time></TableCell><TableCell><StatusBadge domain="alert" status={alert.state} /></TableCell><TableCell>{alert.resolvedAt ? <><time dateTime={alert.resolvedAt}>{formatter.format(new Date(alert.resolvedAt))}</time><p className="mt-1 text-small text-secondary">{alert.resolverLabel}</p></> : "—"}</TableCell></TableRow>)}</TableBody></Table></TableScrollArea></TableCard>
  </div>;
}
