import Link from "next/link";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Pagination, PaginationItem, PaginationLink, PaginationNext, PaginationPrevious } from "@/components/ui/pagination";
import { Select } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { TableCard } from "@/components/ui/table-card";
import { TableScrollArea } from "@/components/ui/table-scroll-area";
import { TableToolbar } from "@/components/ui/table-toolbar";
import type { ActivityListItem } from "@/lib/dal/activity";
import { ACTIVITY_ACTIONS, type ActivityListInput } from "./activity-schema";

const formatter = new Intl.DateTimeFormat("en-GB", { year: "numeric", month: "short", day: "numeric", hour: "2-digit", minute: "2-digit", timeZone: "Europe/Belgrade", timeZoneName: "short" });
const humanize = (value: string) => value.replaceAll("_", " ").replace(/^./, (letter) => letter.toUpperCase());
function url(filters: ActivityListInput, page: number) { const p = new URLSearchParams(); if (filters.actor !== "all") p.set("actor", filters.actor); if (filters.action !== "all") p.set("action", filters.action); if (filters.entity !== "all") p.set("entity", filters.entity); if (filters.from) p.set("from", filters.from); if (filters.to) p.set("to", filters.to); if (page > 1) p.set("page", String(page)); const q = p.toString(); return q ? `/operations/activity?${q}` : "/operations/activity"; }

export function ActivityList({ activities, filters, totalCount, totalPages, isDispatcher }: Readonly<{ activities: readonly ActivityListItem[]; filters: ActivityListInput; totalCount: number; totalPages: number; isDispatcher: boolean }>) {
  const footer = totalPages > 1 ? <Pagination><PaginationItem>{filters.page === 1 ? <PaginationPrevious disabled /> : <PaginationPrevious href={url(filters, filters.page - 1)} />}</PaginationItem>{Array.from({ length: totalPages }, (_, i) => i + 1).map((page) => <PaginationItem key={page}><PaginationLink href={url(filters, page)} active={page === filters.page}>{page}</PaginationLink></PaginationItem>)}<PaginationItem>{filters.page === totalPages ? <PaginationNext disabled /> : <PaginationNext href={url(filters, filters.page + 1)} />}</PaginationItem></Pagination> : undefined;
  const dispatcherActions = new Set(["shipment_created", "shipment_updated", "shipment_assigned", "shipment_status_changed", "shipment_cancelled", "status_request_created", "status_request_approved", "status_request_rejected", "tracking_started", "tracking_stopped"]);
  return <div className="flex min-w-0 flex-col gap-4">
    <form action="/operations/activity" method="get"><TableToolbar leading={<><Select aria-label="Activity actor" name="actor" defaultValue={filters.actor} focusSurface="card"><option value="all">All actors</option><option value="system">System</option><option value="user">Users</option></Select><Select aria-label="Activity action" name="action" defaultValue={filters.action} focusSurface="card"><option value="all">All actions</option>{ACTIVITY_ACTIONS.filter((action) => !isDispatcher || dispatcherActions.has(action)).map((action) => <option key={action} value={action}>{humanize(action)}</option>)}</Select><Select aria-label="Related entity" name="entity" defaultValue={filters.entity} focusSurface="card"><option value="all">All entities</option><option value="shipment">Shipment</option><option value="status_request">Status request</option>{!isDispatcher ? <><option value="vehicle">Vehicle</option><option value="driver">Driver</option><option value="client">Client</option><option value="document">Document</option><option value="maintenance">Maintenance</option><option value="expense">Expense</option></> : null}</Select><div><label className="sr-only" htmlFor="activity-from">Activity from date</label><Input id="activity-from" name="from" type="date" defaultValue={filters.from} focusSurface="card" /></div><div><label className="sr-only" htmlFor="activity-to">Activity to date</label><Input id="activity-to" name="to" type="date" defaultValue={filters.to} focusSurface="card" /></div></>} trailing={<><Button type="submit" variant="outline" focusSurface="card">Apply</Button><Link href="/operations/activity" className="inline-flex min-h-11 items-center justify-center rounded-control px-4 text-label text-secondary hover:bg-background-hover md:min-h-10">Clear</Link></>} /></form>
    <TableCard title="Activity history" description={`${totalCount} ${totalCount === 1 ? "event" : "events"}`} footer={footer}><TableScrollArea aria-label="Operations activity table"><Table><TableHeader><TableRow><TableHead>Time</TableHead><TableHead>Action</TableHead><TableHead>Actor</TableHead><TableHead>Entity</TableHead></TableRow></TableHeader><TableBody>{activities.length === 0 ? <TableRow><TableCell colSpan={4} className="text-center text-secondary">No activity found.</TableCell></TableRow> : activities.map((activity) => <TableRow key={activity.id}><TableCell><time dateTime={activity.occurredAt}>{formatter.format(new Date(activity.occurredAt))}</time></TableCell><TableCell><p className="font-medium">{activity.actionLabel}</p><p className="mt-1 text-small text-secondary">{activity.description}</p></TableCell><TableCell>{activity.actorLabel}</TableCell><TableCell>{activity.entityHref ? <Link className="font-medium text-primary hover:underline" href={activity.entityHref}>{activity.entityLabel}</Link> : activity.entityLabel}</TableCell></TableRow>)}</TableBody></Table></TableScrollArea></TableCard>
  </div>;
}
