"use server";
import { randomUUID } from "node:crypto";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { documentEditSchema, documentLifecycleSchema, uploadCompletionSchema, uploadIntentSchema, type UploadIntentInput } from "@/features/documents/document-schema";
import { requireRole } from "@/lib/dal/auth";
import { changeDocumentLifecycle, finalizeUpload, updateDocument } from "@/lib/dal/operations-documents";
import { createAdminClient } from "@/lib/supabase/admin";
import { createClient } from "@/lib/supabase/server";
import { serverEnv } from "@/lib/env.server";

export type DocumentActionState={status:"idle"|"validation"|"not_found"|"conflict"|"business_rule"|"unauthenticated"|"missing_profile"|"inactive_profile"|"forbidden"|"infrastructure";message:string|null;fieldErrors:Readonly<Record<string,string[]|undefined>>;correlationId:string|null};
const EMPTY={}; const fail=(status:DocumentActionState["status"],message:string,id:string):DocumentActionState=>({status,message,fieldErrors:EMPTY,correlationId:id});
function sanitize(name:string){const extension=name.toLowerCase().match(/\.(pdf|jpe?g|png)$/)?.[0]; if(!extension)return null; const stem=name.slice(0,-extension.length).normalize("NFKC").replace(/[^A-Za-z0-9._-]+/g,"-").replace(/^-+|-+$/g,"")||"document"; return `${stem}${extension===".jpeg"?".jpg":extension}`;}
function extensionMatches(name:string,mime:string){return mime==="application/pdf"?/\.pdf$/i.test(name):mime==="image/png"?/\.png$/i.test(name):/\.(jpg|jpeg)$/i.test(name);}
export async function createDocumentUploadIntent(raw:UploadIntentInput){ const actor=await requireRole("admin","dispatcher","driver"); if(!actor.ok)return{ok:false as const,error:actor.error}; const parsed=uploadIntentSchema.safeParse(raw); if(!parsed.success||!extensionMatches(raw.fileName,raw.mimeType))return{ok:false as const,error:{category:"validation" as const,message:"Check the file and document details."}}; const fileName=sanitize(parsed.data.fileName); if(!fileName)return{ok:false as const,error:{category:"validation" as const,message:"Use a PDF, JPEG, or PNG file."}}; if(actor.data.role==="driver"&&(parsed.data.ownerType!=="shipment"||parsed.data.documentType!=="proof_of_delivery"))return{ok:false as const,error:{category:"forbidden" as const,message:"Access denied."}}; const client=await createClient(); const authorization=await client.rpc("authorize_document_upload_intent",{owner_kind:parsed.data.ownerType,target_owner_id:parsed.data.ownerId,input_document_type:parsed.data.documentType}); if(authorization.error||authorization.data!==true)return{ok:false as const,error:{category:"forbidden" as const,message:"Upload is not permitted for this owner."}}; const documentId=randomUUID(); const filePath=`${parsed.data.ownerType}/${parsed.data.ownerId}/${documentId}/${fileName}`; const {data,error}=await client.storage.from(serverEnv.SUPABASE_DOCUMENTS_BUCKET).createSignedUploadUrl(filePath,{upsert:false}); if(error)return{ok:false as const,error:{category:"infrastructure" as const,message:"Unable to authorize upload."}}; return{ok:true as const,data:{documentId,filePath,fileName,token:data.token}}; }
export async function completeDocumentUpload(raw:unknown){ const parsed=uploadCompletionSchema.safeParse(raw); if(!parsed.success)return{ok:false as const,error:{category:"validation" as const,message:"Upload details are invalid."}}; const result=await finalizeUpload(parsed.data); if(!result.ok){await createAdminClient().storage.from(serverEnv.SUPABASE_DOCUMENTS_BUCKET).remove([parsed.data.filePath]);return result;} revalidatePath("/operations/documents");revalidatePath("/driver/documents");revalidatePath("/operations/alerts");revalidatePath("/operations/notifications");revalidatePath("/operations/activity");return result; }
function editValues(formData:FormData){return{documentId:formData.get("documentId"),expectedUpdatedAt:formData.get("expectedUpdatedAt"),documentType:formData.get("documentType"),validFrom:formData.get("validFrom"),validUntil:formData.get("validUntil")};}
export async function editDocumentAction(_state:DocumentActionState,formData:FormData):Promise<DocumentActionState>{const correlationId=randomUUID();const actor=await requireRole("admin");if(!actor.ok)return fail(actor.error.category,actor.error.message,correlationId);const parsed=documentEditSchema.safeParse(editValues(formData));if(!parsed.success)return{status:"validation",message:"Check the highlighted fields.",fieldErrors:z.flattenError(parsed.error).fieldErrors,correlationId};const result=await updateDocument(parsed.data);if(!result.ok)return fail(result.error.category,result.error.message,correlationId);revalidatePath("/operations/documents");revalidatePath("/operations/alerts");revalidatePath("/operations/notifications");redirect("/operations/documents");}
export async function setDocumentLifecycleAction(_state:DocumentActionState,formData:FormData):Promise<DocumentActionState>{const correlationId=randomUUID();const parsed=documentLifecycleSchema.safeParse({documentId:formData.get("documentId"),expectedUpdatedAt:formData.get("expectedUpdatedAt"),lifecycleStatus:formData.get("lifecycleStatus")});if(!parsed.success)return fail("validation","Document unavailable.",correlationId);const actor=await requireRole(parsed.data.lifecycleStatus==="active"?"admin":"admin","dispatcher");if(!actor.ok)return fail(actor.error.category,actor.error.message,correlationId);if(parsed.data.lifecycleStatus==="active"&&actor.data.role!=="admin")return fail("forbidden","Access denied.",correlationId);const result=await changeDocumentLifecycle(parsed.data.documentId,parsed.data.expectedUpdatedAt,parsed.data.lifecycleStatus);if(!result.ok)return fail(result.error.category,result.error.message,correlationId);revalidatePath("/operations/documents");revalidatePath("/operations/alerts");revalidatePath("/operations/activity");redirect("/operations/documents");}
